### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by leocharrua** [ionic-team/photo-gallery-tutorial-ionic4#2]
Hello. I tested this app in android browser and I get this error:

Camera issue: cordova_not_available

But ionic documentation about camera (https://ionicframework.com/docs/native/camera/) says:

Supported Platforms: Android, Browser, iOS, Windows

How I can get this app work in browser?

Thanks

**Comment by dotNetkow** [comment]
Hey @leocharrua - For the guide that this repo is related to, I just focused on mobile (iOS and Android) at the time. No immediate plans to update it just, but you have some options. 

I see what you mean about supposed web support and to be honest, I'm not sure what's up there. Please check out the newer [PWA Elements](https://github.com/ionic-team/pwa-elements) library, which provides web support for the camera.
