### ISSUE TITLE
Tutorial on documentation is not working

### ISSUE THREAD

**Issue by benjcabalona1029** [ionic-team/photo-gallery-tutorial-ionic4#5]
I tried following the tutorial, and cloning this repository but i am getting the error below
```
Property 'loadSaved' does not exist on type 'PhotoService'.
[ng] 15     this.photoService.loadSaved();
```

**Comment by dotNetkow** [comment]
Looks like you're missing the `loadSaved()` function.  [See here](https://github.com/ionic-team/photo-gallery-tutorial-ionic4/blob/98212d5b8c6278b67d1d34facd074b71f671e743/src/app/services/photo.service.ts#L37).
