### ISSUE TITLE
DevApp is not on Google Play Store

### ISSUE THREAD

**Issue by dnlgrwd87** [ionic-team/photo-gallery-tutorial-ionic4#6]
The section of the tutorial "Install DevApp" states:

"The Ionic DevApp is a free app that makes it easy to run your Ionic app directly on your iOS or Android device. Download it from one of the app stores, then open it on your device:", then gives links to the Google Play Store and the AppStore. However, trying to access the app from the Google Playstore from the link provided, or even from an Android device, it seems that the app no longer exists.

**Comment by dotNetkow** [comment]
thanks - looking into it

**Comment by dotNetkow** [comment]
hi @dnlgrwd87 - after consideration, we've decided to shut down DevApp. We'll share info about this decision officially soon. Basically, the best path forward for Ionic as well as you, our developer base, is to use native tooling. Check out how to do that [here](https://ionicframework.com/docs/building/running). Related to this repo - I have a brand new starter app and First App guide i'm launching later this week, which will replace this one. Stay tuned, and thanks for your patience.
